hydra:
  run:
    dir: log/rl_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: log/rl_${now:%Y%m%d_%H%M%S}
    subdir: ${hydra.job.num}

defaults:
  - env: default
  - agent: ppo
  - log: default
  - _self_

device: cpu
render_mode: null
auto_render: null
