_target_: il.modules.model.diffusion.conditional_UNet1D_model.ConditionalUNet1D
_convert_: all

prediction_state_dim: 4
future_len: 25
time_embed_dim: 128
scene_embed_dim: 128
down_dims:
  - 32
  - 64
  - 128
history_state_dim: 7
road_feature_dim: 2
history_len: 10
road_points: 60
dropout: 0.1
