_target_: il.modules.model.mlp.mlp_trajectory_predictor.MLPTrajectoryPredictor
cfg_history_state_dim: 7
cfg_road_feature_dim: 2
cfg_hidden_dim: 128
cfg_num_encoder_layers: 2
cfg_num_decoder_layers: 2
cfg_num_heads: 4
cfg_dropout: 0.1
history_len: 5
future_len: 25
road_points: 60