hydra:
  run:
    dir: data/${now:%Y%m%d_%H%M%S}
  sweep:
    dir: data/${now:%Y%m%d_%H%M%S}
    subdir: ${hydra.job.num}

defaults:
  - creator: default
  - controller: default
  - preprocess: default
  - env: default
  - _self_

# 运行模式: all=生产+预处理, create=仅生产, preprocess=仅预处理
run_mode: all
