app:
  name: il
  selected_training: ${hydra:runtime.choices.training}
  log_root: log

hydra:
  run:
    dir: ${app.log_root}/${app.name}_${app.selected_training}_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ${app.log_root}/${app.name}_${app.selected_training}_${now:%Y%m%d_%H%M%S}
    subdir: ${hydra.job.num}

defaults:
  - training: train_df   # train_mlp / eval_mlp_open / eval_mlp_close / train_df
  - _self_