app:
  name: il
  selected_training: ${hydra:runtime.choices.training@_global_}_${run_mode}
  log_root: log

hydra:
  run:
    dir: ${app.log_root}/${app.name}_${app.selected_training}_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ${app.log_root}/${app.name}_${app.selected_training}_${now:%Y%m%d_%H%M%S}
    subdir: ${hydra.job.num}

defaults:
  - training@: close_eval_traj_mlp  # train_traj_mlp, close_eval_traj_mlp
  - _self_

run_mode: close_eval # train, validate, test, close_eval
resume_checkpoint: log/il_train_traj_mlp_train_20260511_113803/checkpoint/final.ckpt
