app:
  name: il
  selected_training: ${hydra:runtime.choices.training@_global_}_${run_mode}
  log_root: log

hydra:
  run:
    dir: ${app.log_root}/${app.name}_${app.selected_training}_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ${app.log_root}/${app.name}_${app.selected_training}_${now:%Y%m%d_%H%M%S}
    subdir: ${hydra.job.num}

defaults:
  - training@: train_mlp_traj  # train_mlp_traj, close_eval_mlp_traj
  - _self_