app:
  name: il
  selected_eval: ${hydra:runtime.choices.eval@_global_}_${run_mode}
  log_root: log
  run_id: ${oc.env:RUN_ID,${now:%Y%m%d_%H%M%S}}

hydra:
  run:
    dir: ${app.log_root}/${app.name}_${app.selected_eval}_${app.run_id}
  sweep:
    dir: ${app.log_root}/${app.name}_multirun_runs_${app.run_id}
    subdir: ${hydra.job.num}

defaults:
  # close_eval_traj_mlp, close_eval_traj_diffusion, close_eval_traj_diffusers (choose one)
  - eval@: close_eval_traj_diffusers
  - override hydra/job_logging: custom   # 覆盖 Hydra 内置的 job_logging，避免 Multiple values
  - _self_

run_mode: close_eval
# resume_checkpoint: log/il_train_traj_mlp_train_20260530_104406/checkpoint/final.ckpt
resume_checkpoint: log/il_train_traj_diffusion_train_20260601_084130/checkpoint/final.ckpt

