defaults:
  - /data: default
  - /model: C1DUnet
  - /log: default
  - _self_

device: cuda

trainer:
  _target_: il.training.df_train.DFTrainer
  _convert_: "all"

  checkpoint_path: null

  num_epochs: 1000
  lr: 2e-4
  sample_batch_size: 64
