
defaults:
  - /trainer@trainflow.trainer: default
  - /data@trainflow.data: traj_mlp_data
  - /model@trainflow.model: traj_mlp_model
  - _self_

auto_load_checkpoint: false
resume_checkpoint: log/il_train_mlp_traj_20260509_141637/checkpoint/000-00000055.ckpt
strict: true
weights_only: false