_target_: trainflow.trainer.Trainer
_convert_: "all"
max_epochs: 300
accelerator: auto
devices: null
precision: "32"
strategy: none
gradient_accumulation_steps: 1
gradient_clip_val: null
log_every_n_steps: 5
compiler: false
callbacks:
  - _target_: trainflow.callbacks.ModelCheckpoint
    dirpath: ${hydra:runtime.output_dir}/checkpoint
    monitor: val/loss
    mode: epoch
    save_top_k: 1
    every_n_epochs: 10
  - _target_: trainflow.callbacks.TrainProgressBar
    leave: true
  - _target_: trainflow.callbacks.ValidationProgressBar
    leave: true
  - _target_: trainflow.callbacks.TestProgressBar
    leave: true
  - _target_: trainflow.callbacks.PredictProgressBar
    leave: true
  - _target_: trainflow.callbacks.TimeMonitor
    log_metrics: true
    verbose: false
  - _target_: il.callback.traj_mlp_callback.TrajVisualizationCallback
    log_every_n_epochs: 1
    num_samples: 2
    tag: val_vis/trajectory
    ncols: 1
logger:
  - _target_: trainflow.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}/metrics
    filename: metrics.csv
  - _target_: trainflow.loggers.TensorBoardLogger
    save_dir: ${hydra:runtime.output_dir}/tb
